name: luoyi_apps
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_storage: ^2.0.3
  url_launcher: ^6.1.10
  logger: ^1.2.2
  get: 4.6.5  
  modal_bottom_sheet: ^2.1.2
  date_format: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
